### PR TITLE
update to turf 5.1.6

### PR DESCRIPTION
**Pull request by aliicex**
includes, for example, @turf/random

### CODE REVIEW

**Comment by iursevla** [comment]
Any ETA for this pull request?

**Comment by develar** [comment]
Any news?

**Comment by aliicex** [comment]
You can use my fork, if you like:
https://github.com/geekinaboxx/turf-builder

**Comment by rowanwins** [comment]
Sorry that this took so long. 

If either @geekinaboxx or @iursevla  or @develar would like to help become maintainers of this repo let me know and I'll add you as collaborators.

**Comment by aliicex** [comment]
thanks, @rowanwins . Happy to become a collaborator.

**Comment by iursevla** [comment]
@rowanwins i'll happily collaborate doing the best i can to help the project.

**Pull request merged**
